import type { User, Department, Permission, UserRole } from "./types";

export const mockUsers: User[] = [
  {
    id: "usr_001",
    name: "John Admin",
    email: "john.admin@example.com",
    phone: "(555) 123-4567",
    role: "admin", // admin, manager, agent, viewer
    status: "active", // active, inactive, pending, suspended
    department: "IT", // Assigned Department ID
    permissions: [
      "view_appointments",
      "create_appointments",
      "edit_appointments",
      "delete_appointments",
      "view_users",
      "create_users",
      "edit_users",
      "delete_users",
      "manage_users",
      "view_settings",
      "edit_settings",
      "view_reports",
      "export_data",
      "view_chat_logs",
      "delete_chat_logs",
      "view_email_logs",
      "send_emails",
      "manage_templates",
    ],
    createdAt: "2023-01-15T08:30:00Z",
    lastActive: "2023-05-18T14:25:00Z",
    avatar: "/stylized-jd-initials.png",
    jobTitle: "System Administrator",
    bio: "Experienced system administrator with over 10 years in IT management and customer support systems.",
    location: "New York, NY",
  },
  {
    id: "usr_002",
    name: "Sarah Manager",
    email: "sarah.manager@example.com",
    phone: "(555) 234-5678",
    role: "manager",
    status: "active",
    department: "Customer Support",
    permissions: [
      "view_appointments",
      "create_appointments",
      "edit_appointments",
      "delete_appointments",
      "view_users",
      "view_settings",
      "view_reports",
      "export_data",
      "view_chat_logs",
      "view_email_logs",
      "send_emails",
    ],
    createdAt: "2023-02-10T10:15:00Z",
    lastActive: "2023-05-17T16:45:00Z",
    avatar: "/stylized-sw.png",
    jobTitle: "Support Team Lead",
    location: "Chicago, IL",
  },
  {
    id: "usr_003",
    name: "Mike Agent",
    email: "mike.agent@example.com",
    phone: "(555) 345-6789",
    role: "agent",
    status: "active",
    department: "Customer Support",
    permissions: [
      "view_appointments",
      "create_appointments",
      "edit_appointments",
      "view_chat_logs",
      "view_email_logs",
      "send_emails",
    ],
    createdAt: "2023-03-05T09:20:00Z",
    lastActive: "2023-05-18T11:30:00Z",
    avatar: "/mu-symbol.png",
    jobTitle: "Customer Support Agent",
    location: "Austin, TX",
  },
  {
    id: "usr_004",
    name: "Emily Viewer",
    email: "emily.viewer@example.com",
    role: "viewer",
    status: "active",
    department: "Marketing",
    permissions: ["view_appointments", "view_reports"],
    createdAt: "2023-04-12T14:10:00Z",
    lastActive: "2023-05-16T09:15:00Z",
    avatar: "/abstract-ej-typography.png",
    jobTitle: "Marketing Analyst",
    location: "San Francisco, CA",
  },
  {
    id: "usr_005",
    name: "David Lee",
    email: "david.lee@example.com",
    phone: "(555) 456-7890",
    role: "agent",
    status: "inactive",
    department: "Sales",
    permissions: [
      "view_appointments",
      "create_appointments",
      "edit_appointments",
      "view_chat_logs",
      "view_email_logs",
    ],
    createdAt: "2023-01-20T11:45:00Z",
    lastActive: "2023-04-30T15:20:00Z",
    avatar: "/abstract-dl.png",
    jobTitle: "Sales Representative",
    location: "Denver, CO",
  },
  {
    id: "usr_006",
    name: "Alex Smith",
    email: "alex.smith@example.com",
    role: "agent",
    status: "pending",
    department: "Customer Support",
    permissions: [
      "view_appointments",
      "create_appointments",
      "view_chat_logs",
      "view_email_logs",
    ],
    createdAt: "2023-05-01T08:00:00Z",
    avatar: "/abstract-geometric-as.png",
    jobTitle: "Junior Support Agent",
    location: "Miami, FL",
  },
  {
    id: "usr_007",
    name: "Jessica Roberts",
    email: "jessica.roberts@example.com",
    phone: "(555) 567-8901",
    role: "manager",
    status: "active",
    department: "IT",
    permissions: [
      "view_appointments",
      "create_appointments",
      "edit_appointments",
      "delete_appointments",
      "view_users",
      "view_settings",
      "view_reports",
      "export_data",
      "view_chat_logs",
      "view_email_logs",
      "send_emails",
    ],
    createdAt: "2023-02-15T13:30:00Z",
    lastActive: "2023-05-18T10:10:00Z",
    avatar: "/javascript-code.png",
    jobTitle: "IT Operations Manager",
    location: "Seattle, WA",
  },
  {
    id: "usr_008",
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    role: "agent",
    status: "suspended",
    department: "Customer Support",
    permissions: ["view_appointments", "view_chat_logs"],
    createdAt: "2022-11-10T09:45:00Z",
    lastActive: "2023-03-15T14:20:00Z",
    avatar: "/australian-outback-landscape.png",
    jobTitle: "Support Agent",
    location: "Phoenix, AZ",
  },
];

export const mockDepartments: Department[] = [
  {
    id: "dept_001",
    name: "IT",
    description: "Information Technology department",
  },
  {
    id: "dept_002",
    name: "Customer Support",
    description: "Customer support and service department",
  },
  {
    id: "dept_003",
    name: "Sales",
    description: "Sales and business development",
  },
  {
    id: "dept_004",
    name: "Marketing",
    description: "Marketing and communications",
  },
  {
    id: "dept_005",
    name: "HR",
    description: "Human Resources",
  },
  {
    id: "dept_006",
    name: "Finance",
    description: "Finance and accounting",
  },
  {
    id: "dept_007",
    name: "Operations",
    description: "Business operations",
  },
];

export const permissionDescriptions: Record<Permission, string> = {
  view_appointments: "View appointment details and calendar",
  create_appointments: "Create new appointments",
  edit_appointments: "Modify existing appointments",
  delete_appointments: "Cancel or delete appointments",
  view_users: "View user profiles and information",
  create_users: "Create new user accounts",
  edit_users: "Modify existing user accounts",
  delete_users: "Delete user accounts",
  manage_users: "Manage user roles and permissions",
  view_settings: "View system settings",
  edit_settings: "Modify system settings",
  view_reports: "View analytics and reports",
  export_data: "Export data from the system",
  view_chat_logs: "View conversation history",
  delete_chat_logs: "Delete conversation records",
  view_email_logs: "View email communication history",
  send_emails: "Send emails to customers",
  manage_templates: "Create and edit message templates",
};

export const defaultPermissionsByRole: Record<UserRole, Permission[]> = {
  admin: [
    "view_appointments",
    "create_appointments",
    "edit_appointments",
    "delete_appointments",
    "view_users",
    "create_users",
    "edit_users",
    "delete_users",
    "manage_users",
    "view_settings",
    "edit_settings",
    "view_reports",
    "export_data",
    "view_chat_logs",
    "delete_chat_logs",
    "view_email_logs",
    "send_emails",
    "manage_templates",
  ],
  manager: [
    "view_appointments",
    "create_appointments",
    "edit_appointments",
    "delete_appointments",
    "view_users",
    "view_settings",
    "view_reports",
    "export_data",
    "view_chat_logs",
    "view_email_logs",
    "send_emails",
  ],
  agent: [
    "view_appointments",
    "create_appointments",
    "edit_appointments",
    "view_chat_logs",
    "view_email_logs",
    "send_emails",
  ],
  viewer: ["view_appointments", "view_reports"],
};

export const roleDescriptions: Record<UserRole, string> = {
  admin: "Has full access to all features and settings.",
  manager: "Can manage appointments, users, and view reports.",
  agent: "Can create and manage appointments and communicate with customers.",
  viewer: "Can view appointments and reports.",
};
