import { Permission, UserRole } from "../user-management/types";

export const permissionDescriptions: Record<Permission, string> = {
    view_appointments: "View appointment details and calendar",
    create_appointments: "Create new appointments",
    edit_appointments: "Modify existing appointments",
    delete_appointments: "Cancel or delete appointments",
    view_users: "View user profiles and information",
    create_users: "Create new user accounts",
    edit_users: "Modify existing user accounts",
    delete_users: "Delete user accounts",
    manage_users: "Manage user roles and permissions",
    view_settings: "View system settings",
    edit_settings: "Modify system settings",
    view_reports: "View analytics and reports",
    export_data: "Export data from the system",
    view_chat_logs: "View conversation history",
    delete_chat_logs: "Delete conversation records",
    view_email_logs: "View email communication history",
    send_emails: "Send emails to customers",
    manage_templates: "Create and edit message templates",
};

export const defaultPermissionsByRole: Record<UserRole, Permission[]> = {
    admin: [
        "view_appointments",
        "create_appointments",
        "edit_appointments",
        "delete_appointments",
        "view_users",
        "create_users",
        "edit_users",
        "delete_users",
        "manage_users",
        "view_settings",
        "edit_settings",
        "view_reports",
        "export_data",
        "view_chat_logs",
        "delete_chat_logs",
        "view_email_logs",
        "send_emails",
        "manage_templates",
    ],
    manager: [
        "view_appointments",
        "create_appointments",
        "edit_appointments",
        "delete_appointments",
        "view_users",
        "view_settings",
        "view_reports",
        "export_data",
        "view_chat_logs",
        "view_email_logs",
        "send_emails",
    ],
    agent: [
        "view_appointments",
        "create_appointments",
        "edit_appointments",
        "view_chat_logs",
        "view_email_logs",
        "send_emails",
    ],
    viewer: ["view_appointments", "view_reports"],
};
